version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reallysecret
      POSTGRES_DB: ice_animation
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ice_backend:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: reallysecret
      DATABASE_NAME: ice_animation
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  postgres_data:
